// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package pl.edu.agh.soa.models;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.edu.agh.soa.models.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string last_name = 2;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string faculty = 3;</code>
     * @return The faculty.
     */
    java.lang.String getFaculty();
    /**
     * <code>string faculty = 3;</code>
     * @return The bytes for faculty.
     */
    com.google.protobuf.ByteString
        getFacultyBytes();

    /**
     * <code>string field = 4;</code>
     * @return The field.
     */
    java.lang.String getField();
    /**
     * <code>string field = 4;</code>
     * @return The bytes for field.
     */
    com.google.protobuf.ByteString
        getFieldBytes();

    /**
     * <code>int32 student_id = 5;</code>
     * @return The studentId.
     */
    int getStudentId();

    /**
     * <code>repeated string courses = 7;</code>
     * @return A list containing the courses.
     */
    java.util.List<java.lang.String>
        getCoursesList();
    /**
     * <code>repeated string courses = 7;</code>
     * @return The count of courses.
     */
    int getCoursesCount();
    /**
     * <code>repeated string courses = 7;</code>
     * @param index The index of the element to return.
     * @return The courses at the given index.
     */
    java.lang.String getCourses(int index);
    /**
     * <code>repeated string courses = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the courses at the given index.
     */
    com.google.protobuf.ByteString
        getCoursesBytes(int index);
  }
  /**
   * Protobuf type {@code pl.edu.agh.soa.models.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.edu.agh.soa.models.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      lastName_ = "";
      faculty_ = "";
      field_ = "";
      courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              faculty_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              field_ = s;
              break;
            }
            case 40: {

              studentId_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                courses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              courses_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          courses_ = courses_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.soa.models.StudentOuterClass.internal_static_pl_edu_agh_soa_models_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.soa.models.StudentOuterClass.internal_static_pl_edu_agh_soa_models_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.soa.models.StudentOuterClass.Student.class, pl.edu.agh.soa.models.StudentOuterClass.Student.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 2;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FACULTY_FIELD_NUMBER = 3;
    private volatile java.lang.Object faculty_;
    /**
     * <code>string faculty = 3;</code>
     * @return The faculty.
     */
    public java.lang.String getFaculty() {
      java.lang.Object ref = faculty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faculty_ = s;
        return s;
      }
    }
    /**
     * <code>string faculty = 3;</code>
     * @return The bytes for faculty.
     */
    public com.google.protobuf.ByteString
        getFacultyBytes() {
      java.lang.Object ref = faculty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faculty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD_FIELD_NUMBER = 4;
    private volatile java.lang.Object field_;
    /**
     * <code>string field = 4;</code>
     * @return The field.
     */
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field_ = s;
        return s;
      }
    }
    /**
     * <code>string field = 4;</code>
     * @return The bytes for field.
     */
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STUDENT_ID_FIELD_NUMBER = 5;
    private int studentId_;
    /**
     * <code>int32 student_id = 5;</code>
     * @return The studentId.
     */
    public int getStudentId() {
      return studentId_;
    }

    public static final int COURSES_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList courses_;
    /**
     * <code>repeated string courses = 7;</code>
     * @return A list containing the courses.
     */
    public com.google.protobuf.ProtocolStringList
        getCoursesList() {
      return courses_;
    }
    /**
     * <code>repeated string courses = 7;</code>
     * @return The count of courses.
     */
    public int getCoursesCount() {
      return courses_.size();
    }
    /**
     * <code>repeated string courses = 7;</code>
     * @param index The index of the element to return.
     * @return The courses at the given index.
     */
    public java.lang.String getCourses(int index) {
      return courses_.get(index);
    }
    /**
     * <code>repeated string courses = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the courses at the given index.
     */
    public com.google.protobuf.ByteString
        getCoursesBytes(int index) {
      return courses_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (!getFacultyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, faculty_);
      }
      if (!getFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, field_);
      }
      if (studentId_ != 0) {
        output.writeInt32(5, studentId_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, courses_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (!getFacultyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, faculty_);
      }
      if (!getFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, field_);
      }
      if (studentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, studentId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < courses_.size(); i++) {
          dataSize += computeStringSizeNoTag(courses_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCoursesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.edu.agh.soa.models.StudentOuterClass.Student)) {
        return super.equals(obj);
      }
      pl.edu.agh.soa.models.StudentOuterClass.Student other = (pl.edu.agh.soa.models.StudentOuterClass.Student) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getFaculty()
          .equals(other.getFaculty())) return false;
      if (!getField()
          .equals(other.getField())) return false;
      if (getStudentId()
          != other.getStudentId()) return false;
      if (!getCoursesList()
          .equals(other.getCoursesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + FACULTY_FIELD_NUMBER;
      hash = (53 * hash) + getFaculty().hashCode();
      hash = (37 * hash) + FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getField().hashCode();
      hash = (37 * hash) + STUDENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStudentId();
      if (getCoursesCount() > 0) {
        hash = (37 * hash) + COURSES_FIELD_NUMBER;
        hash = (53 * hash) + getCoursesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.edu.agh.soa.models.StudentOuterClass.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.edu.agh.soa.models.StudentOuterClass.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.edu.agh.soa.models.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.edu.agh.soa.models.Student)
        pl.edu.agh.soa.models.StudentOuterClass.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.soa.models.StudentOuterClass.internal_static_pl_edu_agh_soa_models_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.soa.models.StudentOuterClass.internal_static_pl_edu_agh_soa_models_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.soa.models.StudentOuterClass.Student.class, pl.edu.agh.soa.models.StudentOuterClass.Student.Builder.class);
      }

      // Construct using pl.edu.agh.soa.models.StudentOuterClass.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        lastName_ = "";

        faculty_ = "";

        field_ = "";

        studentId_ = 0;

        courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.soa.models.StudentOuterClass.internal_static_pl_edu_agh_soa_models_Student_descriptor;
      }

      @java.lang.Override
      public pl.edu.agh.soa.models.StudentOuterClass.Student getDefaultInstanceForType() {
        return pl.edu.agh.soa.models.StudentOuterClass.Student.getDefaultInstance();
      }

      @java.lang.Override
      public pl.edu.agh.soa.models.StudentOuterClass.Student build() {
        pl.edu.agh.soa.models.StudentOuterClass.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pl.edu.agh.soa.models.StudentOuterClass.Student buildPartial() {
        pl.edu.agh.soa.models.StudentOuterClass.Student result = new pl.edu.agh.soa.models.StudentOuterClass.Student(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.lastName_ = lastName_;
        result.faculty_ = faculty_;
        result.field_ = field_;
        result.studentId_ = studentId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          courses_ = courses_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.courses_ = courses_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.soa.models.StudentOuterClass.Student) {
          return mergeFrom((pl.edu.agh.soa.models.StudentOuterClass.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.soa.models.StudentOuterClass.Student other) {
        if (other == pl.edu.agh.soa.models.StudentOuterClass.Student.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getFaculty().isEmpty()) {
          faculty_ = other.faculty_;
          onChanged();
        }
        if (!other.getField().isEmpty()) {
          field_ = other.field_;
          onChanged();
        }
        if (other.getStudentId() != 0) {
          setStudentId(other.getStudentId());
        }
        if (!other.courses_.isEmpty()) {
          if (courses_.isEmpty()) {
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoursesIsMutable();
            courses_.addAll(other.courses_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.soa.models.StudentOuterClass.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.soa.models.StudentOuterClass.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 2;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 2;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 2;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object faculty_ = "";
      /**
       * <code>string faculty = 3;</code>
       * @return The faculty.
       */
      public java.lang.String getFaculty() {
        java.lang.Object ref = faculty_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          faculty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string faculty = 3;</code>
       * @return The bytes for faculty.
       */
      public com.google.protobuf.ByteString
          getFacultyBytes() {
        java.lang.Object ref = faculty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faculty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string faculty = 3;</code>
       * @param value The faculty to set.
       * @return This builder for chaining.
       */
      public Builder setFaculty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faculty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string faculty = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaculty() {
        
        faculty_ = getDefaultInstance().getFaculty();
        onChanged();
        return this;
      }
      /**
       * <code>string faculty = 3;</code>
       * @param value The bytes for faculty to set.
       * @return This builder for chaining.
       */
      public Builder setFacultyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        faculty_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object field_ = "";
      /**
       * <code>string field = 4;</code>
       * @return The field.
       */
      public java.lang.String getField() {
        java.lang.Object ref = field_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          field_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string field = 4;</code>
       * @return The bytes for field.
       */
      public com.google.protobuf.ByteString
          getFieldBytes() {
        java.lang.Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string field = 4;</code>
       * @param value The field to set.
       * @return This builder for chaining.
       */
      public Builder setField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string field = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearField() {
        
        field_ = getDefaultInstance().getField();
        onChanged();
        return this;
      }
      /**
       * <code>string field = 4;</code>
       * @param value The bytes for field to set.
       * @return This builder for chaining.
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        field_ = value;
        onChanged();
        return this;
      }

      private int studentId_ ;
      /**
       * <code>int32 student_id = 5;</code>
       * @return The studentId.
       */
      public int getStudentId() {
        return studentId_;
      }
      /**
       * <code>int32 student_id = 5;</code>
       * @param value The studentId to set.
       * @return This builder for chaining.
       */
      public Builder setStudentId(int value) {
        
        studentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 student_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStudentId() {
        
        studentId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCoursesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          courses_ = new com.google.protobuf.LazyStringArrayList(courses_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @return A list containing the courses.
       */
      public com.google.protobuf.ProtocolStringList
          getCoursesList() {
        return courses_.getUnmodifiableView();
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @return The count of courses.
       */
      public int getCoursesCount() {
        return courses_.size();
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @param index The index of the element to return.
       * @return The courses at the given index.
       */
      public java.lang.String getCourses(int index) {
        return courses_.get(index);
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the courses at the given index.
       */
      public com.google.protobuf.ByteString
          getCoursesBytes(int index) {
        return courses_.getByteString(index);
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @param index The index to set the value at.
       * @param value The courses to set.
       * @return This builder for chaining.
       */
      public Builder setCourses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCoursesIsMutable();
        courses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @param value The courses to add.
       * @return This builder for chaining.
       */
      public Builder addCourses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCoursesIsMutable();
        courses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @param values The courses to add.
       * @return This builder for chaining.
       */
      public Builder addAllCourses(
          java.lang.Iterable<java.lang.String> values) {
        ensureCoursesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, courses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCourses() {
        courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string courses = 7;</code>
       * @param value The bytes of the courses to add.
       * @return This builder for chaining.
       */
      public Builder addCoursesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCoursesIsMutable();
        courses_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.edu.agh.soa.models.Student)
    }

    // @@protoc_insertion_point(class_scope:pl.edu.agh.soa.models.Student)
    private static final pl.edu.agh.soa.models.StudentOuterClass.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.edu.agh.soa.models.StudentOuterClass.Student();
    }

    public static pl.edu.agh.soa.models.StudentOuterClass.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pl.edu.agh.soa.models.StudentOuterClass.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_agh_soa_models_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_edu_agh_soa_models_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\025pl.edu.agh.soa.models\"o" +
      "\n\007Student\022\014\n\004name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001" +
      "(\t\022\017\n\007faculty\030\003 \001(\t\022\r\n\005field\030\004 \001(\t\022\022\n\nst" +
      "udent_id\030\005 \001(\005\022\017\n\007courses\030\007 \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pl_edu_agh_soa_models_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_edu_agh_soa_models_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_edu_agh_soa_models_Student_descriptor,
        new java.lang.String[] { "Name", "LastName", "Faculty", "Field", "StudentId", "Courses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
