
package pl.edu.agh.soa.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloSecurityService", targetNamespace = "https://soap.soa.pl/soa/ws", wsdlLocation = "http://localhost:8080/soa/helloSecurity?wsdl")
public class HelloSecurityService
    extends Service
{

    private final static URL HELLOSECURITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSECURITYSERVICE_EXCEPTION;
    private final static QName HELLOSECURITYSERVICE_QNAME = new QName("https://soap.soa.pl/soa/ws", "HelloSecurityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soa/helloSecurity?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSECURITYSERVICE_WSDL_LOCATION = url;
        HELLOSECURITYSERVICE_EXCEPTION = e;
    }

    public HelloSecurityService() {
        super(__getWsdlLocation(), HELLOSECURITYSERVICE_QNAME);
    }

    public HelloSecurityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSECURITYSERVICE_QNAME, features);
    }

    public HelloSecurityService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSECURITYSERVICE_QNAME);
    }

    public HelloSecurityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSECURITYSERVICE_QNAME, features);
    }

    public HelloSecurityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSecurityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecurityDomain
     */
    @WebEndpoint(name = "SecurityPort")
    public SecurityDomain getSecurityPort() {
        return super.getPort(new QName("https://soap.soa.pl/soa/ws", "SecurityPort"), SecurityDomain.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityDomain
     */
    @WebEndpoint(name = "SecurityPort")
    public SecurityDomain getSecurityPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://soap.soa.pl/soa/ws", "SecurityPort"), SecurityDomain.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSECURITYSERVICE_EXCEPTION!= null) {
            throw HELLOSECURITYSERVICE_EXCEPTION;
        }
        return HELLOSECURITYSERVICE_WSDL_LOCATION;
    }

}
