
package pl.edu.agh.soa.soap;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "securityDomain", targetNamespace = "https://soap.soa.pl/soa/ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecurityDomain {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SecurityHello", action = "helloSecurity")
    @WebResult(name = "hiSecurity", targetNamespace = "")
    @RequestWrapper(localName = "SecurityHello", targetNamespace = "https://soap.soa.pl/soa/ws", className = "pl.edu.agh.soa.soap.SecurityHello")
    @ResponseWrapper(localName = "SecurityHelloResponse", targetNamespace = "https://soap.soa.pl/soa/ws", className = "pl.edu.agh.soa.soap.SecurityHelloResponse")
    public String securityHello();

}
